/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swings;

import com.database.AddMobile;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class WelcomeForm extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeForm
     */
    public WelcomeForm() {
        initComponents();
        jTabbedPane1.setIconAt(0,new ImageIcon("C:\\Users\\ACER\\Desktop\\mobile.jpg"));
        jTabbedPane1.setIconAt(1, new ImageIcon("C:\\Users\\ACER\\Desktop\\download.jpg"));
        jTabbedPane1.setIconAt(2,new ImageIcon("C:\\Users\\ACER\\Desktop\\image.png") );
        
        jPanel5.setVisible(false);
        jPanel8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        mobileImeiNumber = new javax.swing.JTextField();
        Company = new javax.swing.JComboBox();
        mobileModel = new javax.swing.JComboBox();
        price = new javax.swing.JTextField();
        warranty = new javax.swing.JComboBox();
        charger = new javax.swing.JCheckBox();
        earphones = new javax.swing.JCheckBox();
        usbCable = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        add1 = new javax.swing.JButton();
        mobileImeiNumber1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        paymentMode = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        customerNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        sellButton = new javax.swing.JButton();
        printBill = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        moblieModel = new javax.swing.JLabel();
        moblieWarranty = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        allCompany = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        appleCompany = new javax.swing.JRadioButton();
        samsungComany = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        motorolaCompany = new javax.swing.JRadioButton();
        lenevoCompany = new javax.swing.JRadioButton();
        xiomiCompany = new javax.swing.JRadioButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gupta Telecom"));

        jLabel1.setText("Welcome:-");

        username.setForeground(new java.awt.Color(0, 0, 204));
        username.setText("name");

        image.setText("Add Image");
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logOut.setText("Log out");
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
        });

        add.setForeground(new java.awt.Color(0, 0, 204));
        add.setText("Add to list");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        mobileImeiNumber.setText("Mobile Imei Number");
        mobileImeiNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileImeiNumberKeyTyped(evt);
            }
        });

        Company.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Company", "Apple", "Samsung", "Motorola", "Lenevo", "Xiomi" }));
        Company.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CompanyItemStateChanged(evt);
            }
        });
        Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyActionPerformed(evt);
            }
        });

        mobileModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Model" }));
        mobileModel.setEnabled(false);

        price.setText("Enter Price");
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceKeyTyped(evt);
            }
        });

        warranty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enter Warranty", "6 months", "1 year", "3 year" }));
        warranty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrantyActionPerformed(evt);
            }
        });

        charger.setText("Charger");

        earphones.setText("Earphones");

        usbCable.setText("USB cable");

        jLabel3.setText("Accessories");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mobileImeiNumber)
                        .addComponent(Company, 0, 235, Short.MAX_VALUE)
                        .addComponent(mobileModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(price)
                        .addComponent(warranty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(charger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(earphones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usbCable))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(mobileImeiNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mobileModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warranty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charger)
                    .addComponent(earphones)
                    .addComponent(usbCable))
                .addGap(18, 18, 18)
                .addComponent(add)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add Mobiles", jPanel2);

        add1.setForeground(new java.awt.Color(0, 0, 204));
        add1.setText("Search");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        mobileImeiNumber1.setText("Mobile Imei Number");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Details"));
        jPanel5.setMaximumSize(new java.awt.Dimension(500, 500));

        jLabel4.setText("Customer's Name");

        paymentMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Payment mode", "Cash", "Paytm", "Card" }));

        jLabel5.setText("Contact Number");

        customerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNumberActionPerformed(evt);
            }
        });
        customerNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerNumberKeyTyped(evt);
            }
        });

        jLabel6.setText("Address:-");

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        sellButton.setText("Sell");
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        printBill.setText("Print");
        printBill.setEnabled(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Moblie Details"));

        moblieModel.setText("Model :-");

        moblieWarranty.setText("Warranty :-");

        jLabel7.setText("Price :- ");

        jLabel8.setText("Company :-");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moblieModel)
                    .addComponent(moblieWarranty)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moblieModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(moblieWarranty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(sellButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printBill))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(customerNumber))
                                .addComponent(paymentMode, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 306, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellButton)
                    .addComponent(printBill)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobileImeiNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(mobileImeiNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sell Mobiles", jPanel4);

        buttonGroup1.add(allCompany);
        allCompany.setText("All");
        allCompany.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                allCompanyStateChanged(evt);
            }
        });
        allCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCompanyActionPerformed(evt);
            }
        });

        jLabel9.setText("Select Company Name");

        buttonGroup1.add(appleCompany);
        appleCompany.setText("Apple");
        appleCompany.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                appleCompanyStateChanged(evt);
            }
        });

        buttonGroup1.add(samsungComany);
        samsungComany.setText("Samsung");
        samsungComany.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                samsungComanyStateChanged(evt);
            }
        });
        samsungComany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samsungComanyActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Mobile List"));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.No.", "Model", "Price", "Quantity", "Warranty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        buttonGroup1.add(motorolaCompany);
        motorolaCompany.setText("Motorola");
        motorolaCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorolaCompanyActionPerformed(evt);
            }
        });

        buttonGroup1.add(lenevoCompany);
        lenevoCompany.setText("Lenevo");
        lenevoCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lenevoCompanyActionPerformed(evt);
            }
        });

        buttonGroup1.add(xiomiCompany);
        xiomiCompany.setText("Xiomi");
        xiomiCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xiomiCompanyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(allCompany)
                .addGap(18, 18, 18)
                .addComponent(appleCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(samsungComany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motorolaCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lenevoCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xiomiCompany)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allCompany)
                    .addComponent(jLabel9)
                    .addComponent(appleCompany)
                    .addComponent(samsungComany)
                    .addComponent(motorolaCompany)
                    .addComponent(lenevoCompany)
                    .addComponent(xiomiCompany))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mobile List", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOut))
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(username))
                    .addComponent(logOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        // TODO add your handling code here:
        logOut.setToolTipText("Name :-    Last login");
    }//GEN-LAST:event_logOutMouseEntered

    private void CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyActionPerformed
        // TODO add your handling code here:
        
        String cmpy =Company.getSelectedItem().toString();
        
        if(!cmpy.equals("Select Company")){
        
            mobileModel.setEnabled(true);
            
        }else{
        
            mobileModel.setEnabled(false);
                
        }
        
        
        
    }//GEN-LAST:event_CompanyActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
        
        jPanel5.setVisible(true);
    }//GEN-LAST:event_add1ActionPerformed

    private void samsungComanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samsungComanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samsungComanyActionPerformed

    private void allCompanyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_allCompanyStateChanged
        // TODO add your handling code here:
        
        check();
    }//GEN-LAST:event_allCompanyStateChanged

    private void appleCompanyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_appleCompanyStateChanged
        // TODO add your handling code here:
        
        check();
    }//GEN-LAST:event_appleCompanyStateChanged

    private void samsungComanyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_samsungComanyStateChanged
        // TODO add your handling code here:
        
        check();
    }//GEN-LAST:event_samsungComanyStateChanged

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
        if(validationOfMobileData()){
        
            int data = AddMobile.addMobile(mobileInfo);
            
            if(data>0){
            
                JOptionPane.showMessageDialog(this, "Added");
            }else{
            
                JOptionPane.showMessageDialog(this, "Plz try again");
            }
        
        }
        
        
    }//GEN-LAST:event_addActionPerformed

    private void warrantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrantyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warrantyActionPerformed

    private void mobileImeiNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileImeiNumberKeyTyped
                 
        int key = (int)evt.getKeyChar();
       if((key<48)||(key>58))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep(); 
        }// TODO add your handling code here: 
        
        String text = mobileImeiNumber.getText();
        if(text.equalsIgnoreCase("mobile imei number")){
            mobileImeiNumber.setText("");
        }
            else
            if(text.isEmpty()){
            mobileImeiNumber.setText("mobile imei number");
            }       // TODO add your handling code here:
        
        
    }//GEN-LAST:event_mobileImeiNumberKeyTyped

    private void priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyTyped
String text = price.getText();
int key = (int)evt.getKeyChar();
        if((key<48)||(key>58))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep(); 
        }        
if(text.equalsIgnoreCase("Enter price")){
            price.setText(" ");
        }
            else
            if(text.isEmpty()){
            price.setText("Enter price");
            }       // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_priceKeyTyped

    private void allCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allCompanyActionPerformed

    private void motorolaCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorolaCompanyActionPerformed
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_motorolaCompanyActionPerformed

    private void lenevoCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lenevoCompanyActionPerformed
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_lenevoCompanyActionPerformed

    private void xiomiCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xiomiCompanyActionPerformed
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_xiomiCompanyActionPerformed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        // TODO add your handling code here:
        if(validationOfSell())
        {
        printBill.setEnabled(true);
        }
    }//GEN-LAST:event_sellButtonActionPerformed

    private void customerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNumberActionPerformed
 
        // TODO add your handling code here:

        
    }//GEN-LAST:event_customerNumberActionPerformed

    private void customerNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNumberKeyTyped
 int key = (int)evt.getKeyChar();
        if((key<48)||(key>58))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_customerNumberKeyTyped

    private void CompanyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CompanyItemStateChanged
        // TODO add your handling code here:
        
       // System.out.println(Company.getSelectedItem().toString());
        
       // Select Model, Iphone 7, Iphone 6s, Iphone 6, Iphone 5s, Iphone 5, j5 2017, j7 2017, s8, s8 plus, c7, g5 plus, g4 plus, z play, c plus, moto m, k5 note, k6 power, phab 2 plus, redmi note 4, redmi 4, redmi note 3, redmi 3s prime,  
    }//GEN-LAST:event_CompanyItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            WelcomeForm w = new WelcomeForm();
            w.setVisible(true);
            w.setAlwaysOnTop(true);
            // w.setUndecorated(true);
            w.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Company;
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JTextArea address;
    private javax.swing.JRadioButton allCompany;
    private javax.swing.JRadioButton appleCompany;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox charger;
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField customerNumber;
    private javax.swing.JCheckBox earphones;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton lenevoCompany;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField mobileImeiNumber;
    private javax.swing.JTextField mobileImeiNumber1;
    private javax.swing.JComboBox mobileModel;
    private javax.swing.JLabel moblieModel;
    private javax.swing.JLabel moblieWarranty;
    private javax.swing.JRadioButton motorolaCompany;
    private javax.swing.JComboBox paymentMode;
    private javax.swing.JTextField price;
    private javax.swing.JButton printBill;
    private javax.swing.JRadioButton samsungComany;
    private javax.swing.JButton sellButton;
    private javax.swing.JCheckBox usbCable;
    private javax.swing.JLabel username;
    private javax.swing.JComboBox warranty;
    private javax.swing.JRadioButton xiomiCompany;
    // End of variables declaration//GEN-END:variables
    private ArrayList<String> mobileInfo;
    private String appleModel[]={"Iphone 7", "Iphone 6s", "Iphone 6", "Iphone 5s", "Iphone 5"};
    private String samsungModel[]={"j5 2017", "j7 2017", "s8", "s8 plus", "c7"};
    private String motorolaModel[]={"g5 plus", "g4 plus", "z play", "c plus", "moto m"};
    private String lenevoModel[]={k5 note, k6 power, phab 2 plus};
    private String xiomiModel[]={};
    
    private void check() {
        
        
    if(allCompany.isSelected()){
    
        jPanel8.setVisible(true);
    }else if(samsungComany.isSelected()){
    
        jPanel8.setVisible(true);
    }else if(appleCompany.isSelected()){
    
       jPanel8.setVisible(true);
    }else if(motorolaCompany.isSelected()){
        jPanel8.setVisible(true);
    }else if(lenevoCompany.isSelected()){
        jPanel8.setVisible(true);
        
    }
    else if(xiomiCompany.isSelected())
    {
        jPanel8.setVisible(true);
    }
    }

    private boolean validationOfMobileData() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
        String imei = this.mobileImeiNumber.getText();
        String company = this.Company.getSelectedItem().toString();
        String model = this.mobileModel.getSelectedItem().toString();
        String price =this.price.getText();
        String warranty = this.warranty.getSelectedItem().toString();
        String ac ;
        String ear="";
        String chr="";
        String usb="";
        
        
        
        if(!(imei.length()==15)){
           JOptionPane.showMessageDialog(this, "Enter valid imei number");
            return false;
        }
        else if(company.equalsIgnoreCase("select company"))
        {
            JOptionPane.showMessageDialog(this, "Enter valid company");
            return false;
        }
        else if(model.equalsIgnoreCase("select model"))
        {
            JOptionPane.showMessageDialog(this, "Enter the model");
            return false;
        }
        else if(price.equalsIgnoreCase("Enter price"))
        {
            JOptionPane.showMessageDialog(this, "Enter the price");
            return false;
        }
     else if(warranty.equalsIgnoreCase("Enter warranty"))
     {
         JOptionPane.showMessageDialog(this, "Enter warranty");
         return false;
     }
        if(earphones.isSelected()){
        
            ear="earphones";
        }else{
        
            ear ="";
        }
        
        if(charger.isSelected()){
        
            chr = "Charger";
        }else{
        
            chr="";
        }
        
        if(usbCable.isSelected()){
        
            usb = "Usb Cable";
        }else{
        
        
            usb="";
        }
        
        ac= ear+" "+chr+" "+usb;
       
        //String s[]= {imei,company,model,price,warranty,ac};
        
        mobileInfo = new ArrayList<>();
        
        mobileInfo.add(imei);
        mobileInfo.add(company);
        mobileInfo.add(model);
        mobileInfo.add(price);
        mobileInfo.add(warranty);
        mobileInfo.add(ac);
        
        
        return true;
    }

    private boolean validationOfSell() {
        String customerName = this.customerName.getText();
        String number = this.customerNumber.getText();
        String payment = this.paymentMode.getSelectedItem().toString();
        String address = this.address.getText();
        
        if(customerName.isEmpty()||customerName.length()<4){
            JOptionPane.showMessageDialog(this, "Enter Valid Name");
            return false;
        }
        else if(payment.equalsIgnoreCase("select payment mode"))
        {
            JOptionPane.showMessageDialog(this, "Select payment mode");
        return false;
        }
        else if(!(number.length()==10))
        {
            JOptionPane.showMessageDialog(this, "Enter a valid Contact number");
        return false;
        }
        else if(!(address.length()>10))
        {
            JOptionPane.showMessageDialog(this, "Enter correct address");
            return false;
        }
        return true;
        //To change body of generated methods, choose Tools | Templates.
    }
}
